name: Generate Chocolatey feed

on:
  push:
    branches: [ main ]
    paths:
      - 'xtunnel/*.nupkg'

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gzip
        run: sudo apt-get update && sudo apt-get install -y gzip

      - name: Generate Chocolatey feed index
        run: |
          cd xtunnel

          # Create Packages file (list of .nupkg)
          ls *.nupkg > Packages

          # Create compressed version
          gzip -kf Packages

      - name: Commit feed index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add xtunnel/Packages*
          git commit -m "Update Chocolatey feed index" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/xtunnel-dev/xtunnel-choco.git HEAD:main